apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams
  namespace: desafio-tam
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - desafio-tam
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: desafio-tam
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: amq-streams-3.2.x
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace